
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'COLOR KIND MATERIAL NUMBER OPERATE QUESTION_HOW QUESTION_MANY SIZEcommand : OPERATE NUMBER articlecommand : QUESTION_HOW QUESTION_MANY articlearticle : attribute articleattribute : COLORattribute : MATERIALattribute : SIZEarticle : KIND'
    
_lr_action_items = {'OPERATE':([0,],[2,]),'QUESTION_HOW':([0,],[3,]),'$end':([1,6,8,12,13,],[0,-1,-7,-2,-3,]),'NUMBER':([2,],[4,]),'QUESTION_MANY':([3,],[5,]),'KIND':([4,5,7,9,10,11,],[8,8,8,-4,-5,-6,]),'COLOR':([4,5,7,9,10,11,],[9,9,9,-4,-5,-6,]),'MATERIAL':([4,5,7,9,10,11,],[10,10,10,-4,-5,-6,]),'SIZE':([4,5,7,9,10,11,],[11,11,11,-4,-5,-6,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'command':([0,],[1,]),'article':([4,5,7,],[6,12,13,]),'attribute':([4,5,7,],[7,7,7,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> OPERATE NUMBER article','command',3,'p_command_operate','ply_shop.py',108),
  ('command -> QUESTION_HOW QUESTION_MANY article','command',3,'p_command_question','ply_shop.py',126),
  ('article -> attribute article','article',2,'p_article_attribute','ply_shop.py',131),
  ('attribute -> COLOR','attribute',1,'p_attribute_color','ply_shop.py',136),
  ('attribute -> MATERIAL','attribute',1,'p_attribute_material','ply_shop.py',141),
  ('attribute -> SIZE','attribute',1,'p_attribute_size','ply_shop.py',146),
  ('article -> KIND','article',1,'p_article_kind','ply_shop.py',151),
]
